# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ruixu/Documents/Flamelet/Bitbucket/flamemaster/radiation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ruixu/Documents/Flamelet/Bitbucket/flamemaster/radiation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ruixu/Documents/Flamelet/Bitbucket/flamemaster/radiation/CMakeFiles /Users/ruixu/Documents/Flamelet/Bitbucket/flamemaster/radiation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ruixu/Documents/Flamelet/Bitbucket/flamemaster/radiation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named radiation

# Build rule for target.
radiation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 radiation
.PHONY : radiation

# fast build rule for target.
radiation/fast:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/build
.PHONY : radiation/fast

src/AbsorptionModel.o: src/AbsorptionModel.cpp.o

.PHONY : src/AbsorptionModel.o

# target to build an object file
src/AbsorptionModel.cpp.o:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/AbsorptionModel.cpp.o
.PHONY : src/AbsorptionModel.cpp.o

src/AbsorptionModel.i: src/AbsorptionModel.cpp.i

.PHONY : src/AbsorptionModel.i

# target to preprocess a source file
src/AbsorptionModel.cpp.i:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/AbsorptionModel.cpp.i
.PHONY : src/AbsorptionModel.cpp.i

src/AbsorptionModel.s: src/AbsorptionModel.cpp.s

.PHONY : src/AbsorptionModel.s

# target to generate assembly for a file
src/AbsorptionModel.cpp.s:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/AbsorptionModel.cpp.s
.PHONY : src/AbsorptionModel.cpp.s

src/Grey.o: src/Grey.cpp.o

.PHONY : src/Grey.o

# target to build an object file
src/Grey.cpp.o:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/Grey.cpp.o
.PHONY : src/Grey.cpp.o

src/Grey.i: src/Grey.cpp.i

.PHONY : src/Grey.i

# target to preprocess a source file
src/Grey.cpp.i:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/Grey.cpp.i
.PHONY : src/Grey.cpp.i

src/Grey.s: src/Grey.cpp.s

.PHONY : src/Grey.s

# target to generate assembly for a file
src/Grey.cpp.s:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/Grey.cpp.s
.PHONY : src/Grey.cpp.s

src/RadiationModel.o: src/RadiationModel.cpp.o

.PHONY : src/RadiationModel.o

# target to build an object file
src/RadiationModel.cpp.o:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/RadiationModel.cpp.o
.PHONY : src/RadiationModel.cpp.o

src/RadiationModel.i: src/RadiationModel.cpp.i

.PHONY : src/RadiationModel.i

# target to preprocess a source file
src/RadiationModel.cpp.i:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/RadiationModel.cpp.i
.PHONY : src/RadiationModel.cpp.i

src/RadiationModel.s: src/RadiationModel.cpp.s

.PHONY : src/RadiationModel.s

# target to generate assembly for a file
src/RadiationModel.cpp.s:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/RadiationModel.cpp.s
.PHONY : src/RadiationModel.cpp.s

src/SNB.o: src/SNB.cpp.o

.PHONY : src/SNB.o

# target to build an object file
src/SNB.cpp.o:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/SNB.cpp.o
.PHONY : src/SNB.cpp.o

src/SNB.i: src/SNB.cpp.i

.PHONY : src/SNB.i

# target to preprocess a source file
src/SNB.cpp.i:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/SNB.cpp.i
.PHONY : src/SNB.cpp.i

src/SNB.s: src/SNB.cpp.s

.PHONY : src/SNB.s

# target to generate assembly for a file
src/SNB.cpp.s:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/SNB.cpp.s
.PHONY : src/SNB.cpp.s

src/WSGG.o: src/WSGG.cpp.o

.PHONY : src/WSGG.o

# target to build an object file
src/WSGG.cpp.o:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/WSGG.cpp.o
.PHONY : src/WSGG.cpp.o

src/WSGG.i: src/WSGG.cpp.i

.PHONY : src/WSGG.i

# target to preprocess a source file
src/WSGG.cpp.i:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/WSGG.cpp.i
.PHONY : src/WSGG.cpp.i

src/WSGG.s: src/WSGG.cpp.s

.PHONY : src/WSGG.s

# target to generate assembly for a file
src/WSGG.cpp.s:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/WSGG.cpp.s
.PHONY : src/WSGG.cpp.s

src/WSGGBordbar.o: src/WSGGBordbar.cpp.o

.PHONY : src/WSGGBordbar.o

# target to build an object file
src/WSGGBordbar.cpp.o:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/WSGGBordbar.cpp.o
.PHONY : src/WSGGBordbar.cpp.o

src/WSGGBordbar.i: src/WSGGBordbar.cpp.i

.PHONY : src/WSGGBordbar.i

# target to preprocess a source file
src/WSGGBordbar.cpp.i:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/WSGGBordbar.cpp.i
.PHONY : src/WSGGBordbar.cpp.i

src/WSGGBordbar.s: src/WSGGBordbar.cpp.s

.PHONY : src/WSGGBordbar.s

# target to generate assembly for a file
src/WSGGBordbar.cpp.s:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/WSGGBordbar.cpp.s
.PHONY : src/WSGGBordbar.cpp.s

src/WSGGJohansson.o: src/WSGGJohansson.cpp.o

.PHONY : src/WSGGJohansson.o

# target to build an object file
src/WSGGJohansson.cpp.o:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/WSGGJohansson.cpp.o
.PHONY : src/WSGGJohansson.cpp.o

src/WSGGJohansson.i: src/WSGGJohansson.cpp.i

.PHONY : src/WSGGJohansson.i

# target to preprocess a source file
src/WSGGJohansson.cpp.i:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/WSGGJohansson.cpp.i
.PHONY : src/WSGGJohansson.cpp.i

src/WSGGJohansson.s: src/WSGGJohansson.cpp.s

.PHONY : src/WSGGJohansson.s

# target to generate assembly for a file
src/WSGGJohansson.cpp.s:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/WSGGJohansson.cpp.s
.PHONY : src/WSGGJohansson.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/radiation.dir/build.make CMakeFiles/radiation.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... radiation"
	@echo "... src/AbsorptionModel.o"
	@echo "... src/AbsorptionModel.i"
	@echo "... src/AbsorptionModel.s"
	@echo "... src/Grey.o"
	@echo "... src/Grey.i"
	@echo "... src/Grey.s"
	@echo "... src/RadiationModel.o"
	@echo "... src/RadiationModel.i"
	@echo "... src/RadiationModel.s"
	@echo "... src/SNB.o"
	@echo "... src/SNB.i"
	@echo "... src/SNB.s"
	@echo "... src/WSGG.o"
	@echo "... src/WSGG.i"
	@echo "... src/WSGG.s"
	@echo "... src/WSGGBordbar.o"
	@echo "... src/WSGGBordbar.i"
	@echo "... src/WSGGBordbar.s"
	@echo "... src/WSGGJohansson.o"
	@echo "... src/WSGGJohansson.i"
	@echo "... src/WSGGJohansson.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

